name: Appium CI (BrowserStack)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  android-bs:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      # Tell BaseTest to skip local Appium
      RUN_ON_BS: "true"
      # BrowserStack credentials
      BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"
      BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
      # Force the SDK to use THIS config file (Android-only devices inside)
      BROWSERSTACK_CONFIG_FILE: "browserstack.yml"
      # Your TestNG suite that includes only Android tests
      SUITE_XML: "testNGSuite/testng_BrowserStack.xml"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Fail fast if secrets missing
        run: |
          [ -n "$BROWSERSTACK_USERNAME" ] && [ -n "$BROWSERSTACK_ACCESS_KEY" ] || {
            echo "::error::Add BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY in repo secrets"; exit 1; }

      - name: Show BrowserStack config being used
        run: |
          echo "Config file: $BROWSERSTACK_CONFIG_FILE"
          echo "----- BEGIN $BROWSERSTACK_CONFIG_FILE -----"
          cat "$BROWSERSTACK_CONFIG_FILE"
          echo "----- END $BROWSERSTACK_CONFIG_FILE -----"
          echo "Any iOS hints in YAML?"
          grep -nEi 'iphone|ipad|platformName:\s*ios' "$BROWSERSTACK_CONFIG_FILE" || echo "No iOS found"

      - name: Run TestNG on BrowserStack (Android only)
        run: |
          mvn -B -ntp -U clean test \
            -PBrowserStack \
            -DRUN_ON_BS=true \
            -Dbrowserstack.config="$BROWSERSTACK_CONFIG_FILE" \
            -Dtestng.suiteXmlFile="$SUITE_XML"

      - name: Upload reports & BrowserStack agent log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bs-android-test-artifacts
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            test-output/**
            reports/**
            logs/browserstack-javaagent.log
            **/browserstack-javaagent.log
          if-no-files-found: warn