
name: Appium CI (BrowserStack)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  android-bs:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      BS_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BS_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BS_APP_URL: "bs://60be83a0baaae51dbac31b21298f5989bc1d3a8d"
      BS_DEVICE: "Google Pixel 7"
      BS_OS_VERSION: "13.0"
      SUITE_XML: "testNGSuite/testng_Smoke.xml"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Fail fast if secrets missing
        run: |
          [ -n "$BS_USERNAME" ] && [ -n "$BS_ACCESS_KEY" ] || {
            echo "::error::Add BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY in repo secrets"; exit 1; }

      - name: Run TestNG on BrowserStack (no local Appium)
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP_URL: "bs://60be83a0baaae51dbac31b21298f5989bc1d3a8d"
          BS_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BS_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BS_APP_URL: "bs://60be83a0baaae51dbac31b21298f5989bc1d3a8d"
          BS_DEVICE: "Google Pixel 7"
          BS_OS_VERSION: "13.0"
          SUITE_XML: "testNGSuite/testng_Smoke.xml"
        run: |
          echo "Running on BrowserStack: $BS_DEVICE ($BS_OS_VERSION)  app: $BS_APP_URL"
          mvn -B -ntp -U clean test \
            -Dtestng.suiteXmlFile="${SUITE_XML}" \
            -DBROWSERSTACK_USERNAME="$BROWSERSTACK_USERNAME" \
            -DBROWSERSTACK_ACCESS_KEY="$BROWSERSTACK_ACCESS_KEY" \
            -DBROWSERSTACK_APP_URL="$BROWSERSTACK_APP_URL" \
            -Dbs.username="$BS_USERNAME" \
            -Dbs.accessKey="$BS_ACCESS_KEY" \
            -Dbs.app="$BS_APP_URL" \
            -Dbs.device="$BS_DEVICE" \
            -Dbs.os_version="$BS_OS_VERSION" \
            -Dbs.project="AppiumFrameworkCloud" \
            -Dbs.build="GH Actions #${{ github.run_number }}" \
            -Dbs.name="Android smoke"

      - name: Upload TestNG/Extent reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bs-android-test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            reports/**
            test-output/**
          if-no-files-found: warn